package org.hadoopinternal.rmi;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;

public class RMIQueryStatusImpl extends UnicastRemoteObject implements RMIQueryStatus {
	private static final long serialVersionUID = -1783519774762066405L;
	
	protected RMIQueryStatusImpl() throws RemoteException {
		super();
	}

	@Override
	public RMIFileStatus getFileStatus(String filename) throws RemoteException {
		RMIFileStatus status=new RMIFileStatus(filename);
		System.out.println("Method getFileStatus Called, return: "+status);
		return status;
	}
}

//下面代码是调用 rmi -keep org.hadoopinternal.rmi.RMIQueryStatusImpl 产生的文件
////Stub class generated by rmic, do not edit.
////Contents subject to change without notice.
//
//package org.hadoopinternal.rmi;
//
//public final class RMIQueryStatusImpl_Stub extends java.rmi.server.RemoteStub
//	implements org.hadoopinternal.rmi.RMIQueryStatus, java.rmi.Remote {
//private static final long serialVersionUID = 2;
//
//private static java.lang.reflect.Method $method_getFileStatus_0;
//
//static {
//	try {
//		$method_getFileStatus_0 = org.hadoopinternal.rmi.RMIQueryStatus.class
//				.getMethod("getFileStatus",
//						new java.lang.Class[] { java.lang.String.class });
//	} catch (java.lang.NoSuchMethodException e) {
//		throw new java.lang.NoSuchMethodError(
//				"stub class initialization failed");
//	}
//}
//
//// constructors
//public RMIQueryStatusImpl_Stub(java.rmi.server.RemoteRef ref) {
//	super(ref);
//}
//
//// methods from remote interfaces
//
//// implementation of getFileStatus(String)
//public org.hadoopinternal.rmi.RMIFileStatus getFileStatus(
//		java.lang.String $param_String_1) throws java.rmi.RemoteException {
//	try {
//		Object $result = ref.invoke(this, $method_getFileStatus_0,
//				new java.lang.Object[] { $param_String_1 },
//				5263112729619635654L);
//		return ((org.hadoopinternal.rmi.RMIFileStatus) $result);
//	} catch (java.lang.RuntimeException e) {
//		throw e;
//	} catch (java.rmi.RemoteException e) {
//		throw e;
//	} catch (java.lang.Exception e) {
//		throw new java.rmi.UnexpectedException(
//				"undeclared checked exception", e);
//	}
//}
//}
